ERROR - 2024-10-14 23:55:54 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'tw32' in C:\xampp\htdocs\tw32\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\tw32\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'tw32', 3306, '', 0)
#1 C:\xampp\htdocs\tw32\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\tw32\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tw32\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tw32\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tw32\app\Controllers\Index.php(35): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\tw32\system\CodeIgniter.php(933): App\Controllers\Index->users()
#7 C:\xampp\htdocs\tw32\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Index))
#8 C:\xampp\htdocs\tw32\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tw32\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\tw32\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\tw32\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'tw32' in C:\xampp\htdocs\tw32\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\tw32\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\tw32\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tw32\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tw32\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tw32\app\Controllers\Index.php(35): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\tw32\system\CodeIgniter.php(933): App\Controllers\Index->users()
#6 C:\xampp\htdocs\tw32\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Index))
#7 C:\xampp\htdocs\tw32\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tw32\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\tw32\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\tw32\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-10-14 23:55:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'tw32'
[Method: GET, Route: index/users]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tblusers`', [], false)
 3 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Index.php(35): CodeIgniter\Model->__call('get', [])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Index->users()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Index))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
